# Generated by Django 5.0.6 on 2024-06-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
        ('books', '0003_alter_book_cover_alter_book_pages'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishers.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher', verbose_name='ناشر'),
        ),
    ]
