# Generated by Django 5.0.6 on 2024-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='logo',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
